import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '../components/nav/navbar'
import Banner from '../components/banner/banner'
import Card from '../components/card/card'
import SectionCards from '../components/card/section-cards'

import { getPopularVideos, getVideos } from "../lib/videos";
const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context) {

  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");
  const popularVideos = await getPopularVideos();
  const travelVideos = await getVideos("indie music");
  // const popularVideos = await getVideos();
  return {
    props: { disneyVideos, travelVideos, productivityVideos }, // will be passed to the page component as props
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='main'>
     <NavBar username= "AngusCarey1@gmail.com"/>

     <Banner 
     title = 'Frozen' subTitle = "A bond between two sisters" imgUrl="/static/Frozen.jpg" />

<div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
        </div>
    </> 
  )
}
